### ISSUE TITLE
remove latitude/longitude bounds

### ISSUE THREAD

**Issue by r0b3rth4ns3n** [jifalops/dart-latlong#11]
the limitation causes at least the following issues with [flutter_map](https://github.com/fleaflet/flutter_map)
fleaflet/flutter_map#468
fleaflet/flutter_map#1201
fleaflet/flutter_map#1338
fleaflet/flutter_map#1452
fleaflet/flutter_map#1582

**Comment by JaffaKetchup** [comment]
Hey @jifalops, huge thanks for getting around to this :)

**Comment by jifalops** [comment]
Sorry that had slipped under my radar
