### ISSUE TITLE
Lat long null error

### ISSUE THREAD

**Issue by Ghoral** [jifalops/dart-latlong#4]
`: Error: The parameter 'center' can't have a value of 'null' because of its type 'LatLng', but the implicit default value is 'null'.
 - 'LatLng' is from 'package:latlong2/latlong.dart' ('/Users/myname/.pub-cache/hosted/pub.dartlang.org/latlong2-0.8.1/lib/latlong.dart').
Try adding either an explicit non-'null' default value or the 'required' modifier.
    LatLng center,
           ^^^^^^
/Users/myame/.pub-cache/hosted/pub.dartlang.org/flutter_map-0.14.0/lib/flutter_map.dart:294:18: Warning: Operand of null-aware operation '??' has type 'LatLng' which excludes null.
 - 'LatLng' is from 'package:latlong2/latlong.dart' ('/Users/mynamme/.pub-cache/hosted/pub.dartlang.org/latlong2-0.8.1/lib/latlong.dart').
  })  : center = center ?? LatLng(50.5, 30.51),`

**Comment by jifalops** [comment]
> `center = center ?? LatLng(50.5, 30.51),`

That looks like an issue with your nullable use of this library and not the library itself. Reopen if necessary.
