### ISSUE TITLE
Distance._round (Unsupported operation: Infinity or NaN toInt)

### ISSUE THREAD

**Issue by msalman2890** [jifalops/dart-latlong#7]
It is a regressed issue on Firebase Crashlytics with the following details.

Non-fatal Exception: io.flutter.plugins.firebase.crashlytics.FlutterError: Unsupported operation: Infinity or NaN toInt. Error thrown null.
       at Distance._round(Distance.dart)
       at Distance.as(Distance.dart:83)
       
       
It is used with the Haversine calculator

**Comment by jifalops** [comment]
fixed in #8
